apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1-frontend
  template:
    metadata:
      labels:
        app: app1-frontend
    spec:
      containers:
        - name: app1-frontend
          image: app1-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: API_URL
              value: http://app2-api:5000
