apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2-api
  template:
    metadata:
      labels:
        app: app2-api
    spec:
      containers:
        - name: app2-api
          image: app2-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
